### ISSUE TITLE
Issue: SharePoint SSO Component

### ISSUE THREAD

**Issue by pm38702003** [microsoft/CopilotStudioSamples#198]
I am succesfully able to use the pre-built solution package.  However when 
bundling the package from the code base I am getting the following error.  Since the customizer isn't loading I am at a loss on debuggin the issue. Any suggestions

sp-pages-assembly_en…e79809187a93.js:190 Could not load pva-sso-application-customizer in require. TypeError: Cannot read properties of undefined (reading 'id')
    at sp-pages-assembly_en…187a93.js:190:12346
    at new Promise (<anonymous>)
    at e.loadComponent (sp-pages-assembly_en…187a93.js:190:12314)
    at sp-pages-assembly_en…187a93.js:190:14535
    at async Promise.all (index 0)
(anonymous)	@	sp-pages-assembly_en…e79809187a93.js:190
sp-pages-assembly_en…e79809187a93.js:315 Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.bbcf8287-ea2d-4bb6-868f-19b9cf4b0812'. Error information is 'Extension failed to load for componentId "bbcf8287-ea2d-4bb6-868f-19b9cf4b0812".'.
    at sp-pages-assembly_en…87a93.js:315:100708
    at async Promise.all (index 0)
(anonymous)	@	sp-pages-assembly_en…e79809187a93.js:315

![image](https://github.com/microsoft/CopilotStudioSamples/assets/3151422/a41ca107-6771-4b54-84f4-fd4cbc724a15)

**Comment by pm38702003** [comment]
mismatch in the devDependencies in the package.json

**Comment by pm38702003** [comment]
mismatch in the devDependencies in the package.json
