### ISSUE TITLE
Issue: SharePoint SSO Component Not able to run npm install

### ISSUE THREAD

**Issue by cliffzhu** [microsoft/CopilotStudioSamples#230]
I seem not able to build it. Could someone help me? I am on Windows 11 and nODE.JS V18.20.4

pm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path C:\Users\myuser\Documents\scripts\CopilotStudioSamples-master\SharePointSSOComponent\node_modules\esbuild
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm error node:internal/errors:865
npm error   const err = new Error(message);
npm error               ^
npm error
npm error Error: Command failed: node C:\Users\myuser\Documents\scripts\CopilotStudioSamples-master\SharePointSSOComponent\node_modules\esbuild\bin\esbuild --version
npm error node:child_process:929
npm error     throw err;
npm error     ^
npm error
npm error <ref *1> Error: spawnSync C:\Users\myuser\Documents\scripts\CopilotStudioSamples-master\SharePointSSOComponent\node_modules\esbuild-windows-64\esbuild.exe UNKNOWN
npm error     at Object.spawnSync (node:internal/child_process:1117:20)
npm error     at spawnSync (node:child_process:876:24)
npm error     at Object.execFileSync (node:child_process:919:15)
npm error     at Object.<anonymous> (C:\Users\myuser\Documents\scripts\CopilotStudioSamples-master\SharePointSSOComponent\node_modules\esbuild\bin\esbuild:177:28)
npm error     at Module._compile (node:internal/modules/cjs/loader:1364:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1203:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1019:12)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
npm error     at node:internal/main/run_main_module:28:49 {
npm error   errno: -4094,
npm error   code: 'UNKNOWN',
npm error   syscall: 'spawnSync C:\\Users\\myuser\\Documents\\scripts\\CopilotStudioSamples-master\\SharePointSSOComponent\\node_modules\\esbuild-windows-64\\esbuild.exe',
npm error   path: 'C:\\Users\\myuser\\Documents\\scripts\\CopilotStudioSamples-master\\SharePointSSOComponent\\node_modules\\esbuild-windows-64\\esbuild.exe',
npm error   spawnargs: [ '--version' ],
npm error   error: [Circular *1],
npm error   status: null,
npm error   signal: null,
npm error   output: null,
npm error   pid: 0,
npm error   stdout: null,
npm error   stderr: null
npm error }
npm error
npm error Node.js v18.20.4
npm error
npm error     at checkExecSyncError (node:child_process:890:11)
npm error     at Object.execFileSync (node:child_process:926:15)
npm error     at validateBinaryVersion (C:\Users\myuser\Documents\scripts\CopilotStudioSamples-master\SharePointSSOComponent\node_modules\esbuild\install.js:89:32)
npm error     at C:\Users\myuser\Documents\scripts\CopilotStudioSamples-master\SharePointSSOComponent\node_modules\esbuild\install.js:240:5 {
npm error   status: 1,
npm error   signal: null,
npm error   output: [
npm error     null,
npm error     Buffer(0) [Uint8Array] [],
npm error     Buffer(1553) [Uint8Array] [
npm error       110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
npm error       114, 111,  99, 101, 115, 115,  58,  57,  50,  57,  13,  10,
npm error        32,  32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114,
npm error       114,  59,  13,  10,  32,  32,  32,  32,  94,  13,  10,  13,
npm error        10,  60, 114, 101, 102,  32,  42,  49,  62,  32,  69, 114,
npm error       114, 111, 114,  58,  32, 115, 112,  97, 119, 110,  83, 121,
npm error       110,  99,  32,  67,  58,  92,  85, 115, 101, 114, 115,  92,
npm error        99, 108, 105, 102, 102,  46, 122, 104, 117,  92,  79, 110,
npm error       101,  68, 114, 105,
npm error       ... 1453 more items
npm error     ]
npm error   ],
npm error   pid: 4032,
npm error   stdout: Buffer(0) [Uint8Array] [],
npm error   stderr: Buffer(1553) [Uint8Array] [
npm error     110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
npm error     114, 111,  99, 101, 115, 115,  58,  57,  50,  57,  13,  10,
npm error      32,  32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114,
npm error     114,  59,  13,  10,  32,  32,  32,  32,  94,  13,  10,  13,
npm error      10,  60, 114, 101, 102,  32,  42,  49,  62,  32,  69, 114,
npm error     114, 111, 114,  58,  32, 115, 112,  97, 119, 110,  83, 121,
npm error     110,  99,  32,  67,  58,  92,  85, 115, 101, 114, 115,  92,
npm error      99, 108, 105, 102, 102,  46, 122, 104, 117,  92,  79, 110,
npm error     101,  68, 114, 105,
npm error     ... 1453 more items
npm error   ]
npm error }
npm error
npm error Node.js v18.20.4
npm error A complete log of this run can be found in: C:\Users\myuser\AppData\Local\npm-cache\_logs\2024-07-24T17_43_05_329Z-debug-0.log

**Comment by adilei** [comment]
I don't know why esbuild isn't running in your environment - but it shouldn't be related to the sample. Until this is resolved, maybe use the pre-built package? You can find it in the setup instructions.

**Comment by vtran4270** [comment]
Hello Adilei:

I ran into the issue below when trying to run the 'npm install' command.  I tried it under the following node versions: 16.20.2, 18.20.4 and 20.17.0.

Please advise, thanks
-----------------------------------------------------

npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\XXX\\CopilotStudioSamples-master\\SharePointSSOComponent\\node_modules\\eslint-plugin-tsdoc\\node_modules\\@microsoft\\tsdoc-config\\lib\\__tests__\\assets\\p4'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path C:\Users\XXX\CopilotStudioSamples-master\SharePointSSOComponent\node_modules\abort-controller-es5
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c npm run postinstall:commonjs && npm run postinstall:esm
npm error > abort-controller-es5@2.0.1 postinstall:commonjs
npm error > node ./scripts/esbuild.mjs abort-controller ./src/index.js cjs ./lib/index.bundled.js && babel ./lib/index.bundled.js --config-file ./babel.config.commonjs.json --out-file ./lib/index.js
npm error 'Company' is not recognized as an internal or external command,
npm error operable program or batch file.
npm error node:internal/modules/cjs/loader:1143
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module 'C:\Users\XXX\@babel\cli\bin\babel.js'
npm error     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
npm error     at Module._load (node:internal/modules/cjs/loader:981:27)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
npm error     at node:internal/main/run_main_module:28:49 {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: []
npm error }
npm error
npm error Node.js v18.20.4
